controller_list:
       - name: timon/arm_controller
         action_ns: follow_joint_trajectory
         type: FollowJointTrajectory
         default: true
         joints:
            - id_1
            - id_2
            - id_3
            - id_4
            - id_5
