id_1:
  ID: 1
  Return_Delay_Time: 0
  Operating_Mode: 3
  Goal_Velocity: 100
  Profile_Acceleration: 300
  Profile_Velocity: 100

id_2:
  ID: 2
  Return_Delay_Time: 0
  Operating_Mode: 3
  Goal_Velocity: 100
  Profile_Acceleration: 300
  Profile_Velocity: 100

id_3:
  ID: 3
  Return_Delay_Time: 0
  Operating_Mode: 3
  Goal_Velocity: 100
  Profile_Acceleration: 300
  Profile_Velocity: 100

id_4:
  ID: 4
  Return_Delay_Time: 0
  Operating_Mode: 3
  Goal_Velocity: 100
  Profile_Acceleration: 300
  Profile_Velocity: 100

id_5:
  ID: 5
  Return_Delay_Time: 0
  Operating_Mode: 3
  Goal_Velocity: 100
  Profile_Acceleration: 300
  Profile_Velocity: 100

