debug: true
image_topic: /timon/camera/image_raw
enable_tf: true
marker_dictionary: 0
markers_length: [58] # length in mm.
markers_58: [4] # Markers id with length 90.
camera_matrix: [851.23144, 0.0, 325.47841, 0.0, 852.46834, 253.47602, 0.0, 0.0, 1.0]
camera_distortion: [-0.107958, 0.072164, 0.000900, -0.001374, 0.000000]
static_variance: false
static_camera_transform: false
static_marker: false
static_markers_id: [4]
map_tf_name: box_link
base_tf_name: world
marker_tf_name: tag_aruco_
camera_tf_name: virtual_camera
pose_topic: pose
robot_as_parent: true
variance_matrix: [0.01, 0, 0, 0, 0, 0, 
                  0, 0.01, 0, 0, 0, 0,
                  0, 0, 0.01, 0, 0, 0,
                  0, 0, 0, 0.01, 0, 0,
                  0, 0, 0, 0, 0.01, 0,
                  0, 0, 0, 0, 0, 0.01]