joint3_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: claw_1f
    joint_speed: 1.0
    motor:
        id: 1
        init: 0
        min: 0
        max: 4095
        
joint4_controller:
    controller:
        package: dynamixel_controllers
        module: joint_torque_controller
        type: JointTorqueController
    joint_name: traction_1f
    joint_speed: 1.0
    motor:
        id: 3
        init: 0
        min: 0
        max: 2047
        
joint5_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint_1f
    joint_speed: 1.0
    motor:
        id: 4
        init: 0
        min: 0
        max: 4095