joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

joint1_position_controller:
  type: position_controllers/JointPositionController
  joint: timon_joint1
  pid: {p: 100.0, i: 1, d: 1}

joint4_position_controller:
  type: position_controllers/JointPositionController
  joint: timon_joint4
  pid: {p: 100.0, i: 1, d: 1}

joint7_position_controller:
  type: position_controllers/JointPositionController
  joint: timon_joint7 
  pid: {p: 100.0, i: 1, d: 1}

joint9_position_controller:
  type: position_controllers/JointPositionController
  joint: timon_joint9
  pid: {p: 100.0, i: 1, d: 1}