joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     - timon_joint1
     - timon_joint4
     - timon_joint7
     - timon_joint9
     - timon_joint11
  gains:
      timon_joint1: { p: 100, d: 1, i: 1, i_clamp: 1 }
      timon_joint4: { p: 100, d: 1, i: 1, i_clamp: 1 }
      timon_joint7: { p: 100, d: 1, i: 1, i_clamp: 1 }
      timon_joint9: { p: 100, d: 1, i: 1, i_clamp: 1 }
      timon_joint11: { p: 100, d: 1, i: 1, i_clamp: 1 }
  
  state_publish_rate: 25 