controller_list:
  - name: fake_timon_arm_controller
    joints:
      - timon_joint2
      - timon_joint5
      - timon_joint8
      - timon_joint10
  - name: fake_timon_hand_controller
    joints:
      - timon_hand_joint_1